### ISSUE TITLE
"import irtk" throws the exception "no module named irtk" when installed.

### ISSUE THREAD

**Issue by isaaccasm** [BioMedIA/python-irtk#2]
After installing the library using the command: conda install -c kevin-keraudren python-irtk; as suggested in the installation guidelines, it seems that the conda module for irtk does not contain python files. I was expecting something like: ~/miniconda2/pkgs/irtk-1.0-0/lib/python2.7/site-packages/irtk to exist and to contain an __init__.py file, but I may be wrong. I believe that as a consequence, "import irtk" throws the exception "no module named irtk".

I have created a conda environment only for this module and have checked that the module and its dependencies (vtk, tbb and libpng) are installed. I also tried to import vtk and other python libraries that I installed later with no problem.

I have tried to manually download the python files from the git repository and put them in the conda environment. This produces the exception: "ImportError: libvtkHybrid.so.5.10: cannot open shared object file: No such file or directory."

Anyhow, the project is nice :).

**Comment by kevin-keraudren** [comment]
Please refer to Issue https://github.com/BioMedIA/python-irtk/issues/3 .
